version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - 8000
    volumes:
     - ./web:/web

  nginx:
    depends_on:
     - web
    restart: always
    build: ./nginx
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - /etc/letsencrypt/live/programmerdays.com/fullchain.pem:/etc/letsencrypt/live/programmerdays.com/fullchain.pem
      - /etc/letsencrypt/live/programmerdays.com/privkey.pem:/etc/letsencrypt/live/programmerdays.com/privkey.pem