version: '2'

services:
  db:
    build: ./db
    volumes:
     - $POSTS_DIR:/posts:ro
     - $DB_DIR:/db:rw

  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    volumes:
     - $DB_DIR:/db
     - $PAGES_DIR:/pages:ro
     - $POSTS_DIR:/posts:ro

  nginx:
    depends_on:
     - web
    restart: always
    build:
      context:
        ./nginx
      args:
      - CONF_FILE=$NGINX_CONF_FILE
    ports:
     - "$NGINX_PORT:$NGINX_PORT"
     - "443:443"
    volumes:
      - $LETS_ENCRYPT_DIR:/etc/letsencrypt/live/programmerdays.com
      - $ACME_CHALLENGE_DIR:/usr/share/nginx/html/.well-known/acme-challenge

